/*---------------------------------------------------------------------------------------------
 *  Copyright (c) RoboAgent. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

/*---------------------------------------------------------------------------------------------
 *  RoboAgent — STM32 project generator (pure: spec → files, no vscode).
 *
 *  Emits a self-contained CMake (or Makefile) project for arm-none-eabi-gcc with the correct
 *  -mcpu / -mfpu / -mfloat-abi flags for the chosen core, a linker-script stub sized from the
 *  MCU database, a startup placeholder, `Core/Src/main.c`, and the .vscode files that make
 *  IntelliSense, tasks and debugging (Cortex-Debug or cpptools+OpenOCD) work out of the box.
 *  Libraries get `add_library(... STATIC ...)` and no main/linker/startup.
 *--------------------------------------------------------------------------------------------*/

import { FileSet, jsonFile, toIdentifier } from '../scaffold';
import { cpuFlags, ResolvedStm32Target } from './mcuDatabase';

export type Stm32ProjectKind = 'executable' | 'library';
export type Stm32Toolchain = 'cmake' | 'make';

export interface Stm32ProjectSpec {
	readonly name: string;
	readonly target: ResolvedStm32Target;
	readonly kind: Stm32ProjectKind;
	readonly toolchain: Stm32Toolchain;
	/** OpenOCD interface script (`stlink`, `jlink`, `cmsis-dap`). */
	readonly openocdInterface: string;
}

const MARKER = 'Generated by RoboAgent (Mode: STM32). Edit freely — this header only helps RoboAgent recognise the project.';

export function generateStm32Project(spec: Stm32ProjectSpec): FileSet {
	const files = new Map<string, string>();
	const id = toIdentifier(spec.name);
	const isExe = spec.kind === 'executable';
	const t = spec.target;

	if (spec.toolchain === 'cmake') {
		files.set('CMakeLists.txt', cmakeLists(spec, id));
		files.set('cmake/arm-none-eabi.cmake', toolchainFile());
	} else {
		files.set('Makefile', makefile(spec, id));
	}

	if (isExe) {
		files.set('Core/Inc/main.h', mainHeader(t));
		files.set('Core/Src/main.c', mainSource(spec, t));
		files.set(`startup_${t.define.toLowerCase()}.s`, startupPlaceholder(t));
		files.set(`${t.part}_FLASH.ld`, linkerScript(t));
	} else {
		files.set(`Inc/${id}.h`, libraryHeader(id));
		files.set(`Src/${id}.c`, librarySource(id));
	}

	files.set('.vscode/c_cpp_properties.json', cCppProperties(spec, t));
	files.set('.vscode/tasks.json', tasksJson(spec, id));
	if (isExe) {
		files.set('.vscode/launch.json', launchJson(spec, id));
	}
	files.set('.vscode/settings.json', jsonFile({ 'roboagent.mode': 'stm32', 'files.associations': { '*.h': 'c' }, 'C_Cpp.default.configurationProvider': '' }));
	files.set('.gitignore', 'build/\n*.elf\n*.bin\n*.hex\n*.map\n');
	files.set('README.md', readme(spec, id));
	files.set('.roboagent/project.json', jsonFile({ controlLevel: 'low', target: 'stm32', name: id, part: t.part, kind: spec.kind, toolchain: spec.toolchain, createdWith: 'roboagent-mode-stm32' }));
	return files;
}

// --- CMake ------------------------------------------------------------------

function cmakeLists(spec: Stm32ProjectSpec, id: string): string {
	const t = spec.target;
	const flags = cpuFlags(t).join(' ');
	const common = `cmake_minimum_required(VERSION 3.22)

# ${MARKER}
# Target: ${t.part} (${t.family.label}${t.exact ? '' : ' — part not in RoboAgent catalog: verify memory sizes and defines'})
set(CMAKE_TOOLCHAIN_FILE \${CMAKE_CURRENT_SOURCE_DIR}/cmake/arm-none-eabi.cmake)

project(${id} C ASM)
set(CMAKE_C_STANDARD 11)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

set(MCU_FLAGS ${flags})
add_compile_options(\${MCU_FLAGS} -Wall -Wextra -ffunction-sections -fdata-sections -fno-common)
add_compile_options("$<$<CONFIG:Debug>:-Og;-g3>")
add_compile_definitions(${t.define} USE_HAL_DRIVER)
`;
	if (spec.kind === 'library') {
		return common + `
add_library(\${PROJECT_NAME} STATIC
  Src/${id}.c
)
target_include_directories(\${PROJECT_NAME} PUBLIC Inc)
`;
	}
	return common + `
set(LINKER_SCRIPT \${CMAKE_CURRENT_SOURCE_DIR}/${t.part}_FLASH.ld)

add_executable(\${PROJECT_NAME}.elf
  Core/Src/main.c
  startup_${t.define.toLowerCase()}.s
)
target_include_directories(\${PROJECT_NAME}.elf PRIVATE Core/Inc)
target_link_options(\${PROJECT_NAME}.elf PRIVATE
  \${MCU_FLAGS}
  -T\${LINKER_SCRIPT}
  --specs=nano.specs --specs=nosys.specs
  -Wl,--gc-sections -Wl,-Map=\${PROJECT_NAME}.map,--cref
)

# bin/hex artifacts next to the .elf
add_custom_command(TARGET \${PROJECT_NAME}.elf POST_BUILD
  COMMAND \${CMAKE_OBJCOPY} -O ihex   $<TARGET_FILE:\${PROJECT_NAME}.elf> \${PROJECT_NAME}.hex
  COMMAND \${CMAKE_OBJCOPY} -O binary $<TARGET_FILE:\${PROJECT_NAME}.elf> \${PROJECT_NAME}.bin
  COMMAND \${CMAKE_SIZE} $<TARGET_FILE:\${PROJECT_NAME}.elf>
)
`;
}

function toolchainFile(): string {
	return `# arm-none-eabi-gcc toolchain file — ${MARKER}
# The toolchain is looked up on PATH unless TOOLCHAIN_PATH (a directory) is given:
#   cmake -DTOOLCHAIN_PATH=/opt/gcc-arm-none-eabi/bin ...
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(TOOLCHAIN_PREFIX arm-none-eabi-)
if(DEFINED TOOLCHAIN_PATH AND NOT TOOLCHAIN_PATH STREQUAL "")
  set(TOOLCHAIN_PREFIX \${TOOLCHAIN_PATH}/\${TOOLCHAIN_PREFIX})
endif()

set(CMAKE_C_COMPILER   \${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_CXX_COMPILER \${TOOLCHAIN_PREFIX}g++)
set(CMAKE_ASM_COMPILER \${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_OBJCOPY      \${TOOLCHAIN_PREFIX}objcopy)
set(CMAKE_SIZE         \${TOOLCHAIN_PREFIX}size)

# Try-compile a static library: a bare-metal target cannot link a test executable.
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
`;
}

// --- Makefile ---------------------------------------------------------------

function makefile(spec: Stm32ProjectSpec, id: string): string {
	const t = spec.target;
	const flags = cpuFlags(t).join(' ');
	const head = `# ${MARKER}
# Target: ${t.part} (${t.family.label})
TARGET     := ${id}
BUILD_DIR  := build
TOOLCHAIN_PATH ?=
PREFIX     := $(if $(TOOLCHAIN_PATH),$(TOOLCHAIN_PATH)/,)arm-none-eabi-
CC         := $(PREFIX)gcc
AR         := $(PREFIX)ar
OBJCOPY    := $(PREFIX)objcopy
SIZE       := $(PREFIX)size

MCU_FLAGS  := ${flags}
CFLAGS     := $(MCU_FLAGS) -Wall -Wextra -Og -g3 -ffunction-sections -fdata-sections -fno-common -D${t.define} -DUSE_HAL_DRIVER
`;
	if (spec.kind === 'library') {
		return head + `CFLAGS     += -IInc
SRCS       := $(wildcard Src/*.c)
OBJS       := $(SRCS:%.c=$(BUILD_DIR)/%.o)

all: $(BUILD_DIR)/lib$(TARGET).a

$(BUILD_DIR)/lib$(TARGET).a: $(OBJS)
\t$(AR) rcs $@ $^

$(BUILD_DIR)/%.o: %.c
\t@mkdir -p $(dir $@)
\t$(CC) $(CFLAGS) -c $< -o $@

clean:
\trm -rf $(BUILD_DIR)

.PHONY: all clean
`;
	}
	return head + `CFLAGS     += -ICore/Inc
LDSCRIPT   := ${t.part}_FLASH.ld
LDFLAGS    := $(MCU_FLAGS) -T$(LDSCRIPT) --specs=nano.specs --specs=nosys.specs -Wl,--gc-sections -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref
SRCS       := $(wildcard Core/Src/*.c)
ASMS       := startup_${t.define.toLowerCase()}.s
OBJS       := $(SRCS:%.c=$(BUILD_DIR)/%.o) $(ASMS:%.s=$(BUILD_DIR)/%.o)

all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin

$(BUILD_DIR)/$(TARGET).elf: $(OBJS) $(LDSCRIPT)
\t$(CC) $(OBJS) $(LDFLAGS) -o $@
\t$(SIZE) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf
\t$(OBJCOPY) -O ihex $< $@

$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf
\t$(OBJCOPY) -O binary $< $@

$(BUILD_DIR)/%.o: %.c
\t@mkdir -p $(dir $@)
\t$(CC) $(CFLAGS) -c $< -o $@

$(BUILD_DIR)/%.o: %.s
\t@mkdir -p $(dir $@)
\t$(CC) $(CFLAGS) -x assembler-with-cpp -c $< -o $@

clean:
\trm -rf $(BUILD_DIR)

.PHONY: all clean
`;
}

// --- Sources ----------------------------------------------------------------

function mainHeader(t: ResolvedStm32Target): string {
	return `/* ${MARKER} */
#ifndef MAIN_H
#define MAIN_H

#include <stdint.h>

/* Add "#include \\"${t.family.cmsisPrefix}_hal.h\\"" once the STM32Cube HAL / CMSIS device pack is in the project. */

void Error_Handler(void);

#endif /* MAIN_H */
`;
}

function mainSource(spec: Stm32ProjectSpec, t: ResolvedStm32Target): string {
	return `/* ${MARKER}
 * ${spec.name} — ${t.part} (${t.family.label}, ${t.core})
 *
 * This skeleton links and runs without vendor headers: it toggles a counter in an idle loop.
 * Replace the body with HAL/LL code once the CMSIS device pack for ${t.define} is added
 * (Core/Inc, Drivers/…) — the CMake flags, linker script and startup file already match the part.
 */
#include "main.h"

static volatile uint32_t tick;

int main(void)
{
    /* SystemInit()/HAL_Init() go here once the device pack is present. */
    for (;;) {
        tick++;
        for (volatile uint32_t i = 0; i < 100000u; i++) { __asm__ volatile ("nop"); }
    }
}

void Error_Handler(void)
{
    __asm__ volatile ("bkpt #0");
    for (;;) { }
}
`;
}

function startupPlaceholder(t: ResolvedStm32Target): string {
	return `/* ${MARKER}
 * Minimal startup for ${t.part}: vector table (stack pointer + Reset), .data copy, .bss clear.
 * Replace with the CMSIS device startup file (startup_${t.define.toLowerCase()}.s from the
 * STM32Cube${t.family.id} package) to get the full interrupt vector table.
 */
  .syntax unified
  .cpu ${t.flags.mcpu}
  .thumb

  .section .isr_vector,"a",%progbits
  .type g_pfnVectors, %object
g_pfnVectors:
  .word _estack
  .word Reset_Handler
  .word Default_Handler        /* NMI */
  .word Default_Handler        /* HardFault */
  .size g_pfnVectors, .-g_pfnVectors

  .section .text.Reset_Handler
  .weak Reset_Handler
  .type Reset_Handler, %function
Reset_Handler:
  ldr   r0, =_estack
  mov   sp, r0
  /* copy .data from flash */
  ldr   r0, =_sdata
  ldr   r1, =_edata
  ldr   r2, =_sidata
  movs  r3, #0
  b     1f
0:ldr   r4, [r2, r3]
  str   r4, [r0, r3]
  adds  r3, r3, #4
1:adds  r4, r0, r3
  cmp   r4, r1
  bcc   0b
  /* zero .bss */
  ldr   r2, =_sbss
  ldr   r4, =_ebss
  movs  r3, #0
  b     3f
2:str   r3, [r2]
  adds  r2, r2, #4
3:cmp   r2, r4
  bcc   2b
  bl    main
  b     .
  .size Reset_Handler, .-Reset_Handler

  .section .text.Default_Handler,"ax",%progbits
Default_Handler:
  b     .
  .size Default_Handler, .-Default_Handler
`;
}

function linkerScript(t: ResolvedStm32Target): string {
	return `/* ${MARKER}
 * Linker script stub for ${t.part}: ${t.flashKb} KB flash @ 0x08000000, ${t.ramKb} KB RAM @ 0x20000000.
 * ${t.exact ? 'Sizes come from the RoboAgent MCU catalog; check them against the datasheet for your exact variant.' : 'THIS PART IS NOT IN THE ROBOAGENT CATALOG — the sizes below are conservative defaults. Fix them from the datasheet.'}
 * Replace with the STM32Cube-generated ${t.part}_FLASH.ld for the full memory map (CCM, DTCM, backup SRAM…).
 */
ENTRY(Reset_Handler)

_estack = ORIGIN(RAM) + LENGTH(RAM);
_Min_Heap_Size  = 0x200;
_Min_Stack_Size = 0x400;

MEMORY
{
  FLASH (rx)  : ORIGIN = 0x08000000, LENGTH = ${t.flashKb}K
  RAM   (xrw) : ORIGIN = 0x20000000, LENGTH = ${t.ramKb}K
}

SECTIONS
{
  .isr_vector : { . = ALIGN(4); KEEP(*(.isr_vector)) . = ALIGN(4); } >FLASH
  .text       : { . = ALIGN(4); *(.text) *(.text*) *(.glue_7) *(.glue_7t) *(.eh_frame) KEEP(*(.init)) KEEP(*(.fini)) . = ALIGN(4); _etext = .; } >FLASH
  .rodata     : { . = ALIGN(4); *(.rodata) *(.rodata*) . = ALIGN(4); } >FLASH
  .ARM.extab  : { *(.ARM.extab* .gnu.linkonce.armextab.*) } >FLASH
  .ARM        : { __exidx_start = .; *(.ARM.exidx*) __exidx_end = .; } >FLASH
  .preinit_array : { PROVIDE_HIDDEN(__preinit_array_start = .); KEEP(*(.preinit_array*)) PROVIDE_HIDDEN(__preinit_array_end = .); } >FLASH
  .init_array : { PROVIDE_HIDDEN(__init_array_start = .); KEEP(*(SORT(.init_array.*))) KEEP(*(.init_array*)) PROVIDE_HIDDEN(__init_array_end = .); } >FLASH
  .fini_array : { PROVIDE_HIDDEN(__fini_array_start = .); KEEP(*(SORT(.fini_array.*))) KEEP(*(.fini_array*)) PROVIDE_HIDDEN(__fini_array_end = .); } >FLASH

  _sidata = LOADADDR(.data);
  .data : { . = ALIGN(4); _sdata = .; *(.data) *(.data*) . = ALIGN(4); _edata = .; } >RAM AT> FLASH

  . = ALIGN(4);
  .bss : { _sbss = .; __bss_start__ = _sbss; *(.bss) *(.bss*) *(COMMON) . = ALIGN(4); _ebss = .; __bss_end__ = _ebss; } >RAM

  ._user_heap_stack : { . = ALIGN(8); PROVIDE(end = .); PROVIDE(_end = .); . = . + _Min_Heap_Size; . = . + _Min_Stack_Size; . = ALIGN(8); } >RAM

  /DISCARD/ : { libc.a (*) libm.a (*) libgcc.a (*) }
  .ARM.attributes 0 : { *(.ARM.attributes) }
}
`;
}

function libraryHeader(id: string): string {
	const guard = `${id.toUpperCase()}_H`;
	return `/* ${MARKER} */
#ifndef ${guard}
#define ${guard}

#include <stdint.h>

/** Initialise the ${id} library. */
void ${id}_init(void);

/** Example API: returns the number of times ${id}_tick() was called. */
uint32_t ${id}_tick(void);

#endif /* ${guard} */
`;
}

function librarySource(id: string): string {
	return `/* ${MARKER} */
#include "${id}.h"

static uint32_t s_ticks;

void ${id}_init(void)
{
    s_ticks = 0u;
}

uint32_t ${id}_tick(void)
{
    return ++s_ticks;
}
`;
}

// --- .vscode ----------------------------------------------------------------

function cCppProperties(spec: Stm32ProjectSpec, t: ResolvedStm32Target): string {
	const isExe = spec.kind === 'executable';
	return jsonFile({
		version: 4,
		configurations: [{
			name: 'STM32',
			compilerPath: 'arm-none-eabi-gcc',
			compilerArgs: cpuFlags(t),
			includePath: isExe ? ['${workspaceFolder}/Core/Inc', '${workspaceFolder}/Drivers/**'] : ['${workspaceFolder}/Inc'],
			defines: [t.define, 'USE_HAL_DRIVER'],
			cStandard: 'c11',
			cppStandard: 'c++17',
			intelliSenseMode: 'linux-gcc-arm',
			...(spec.toolchain === 'cmake' ? { compileCommands: '${workspaceFolder}/build/compile_commands.json' } : {}),
		}],
	});
}

/** The build command lines; shared with the STM32 provider so the Build button and tasks.json agree. */
export function stm32BuildCommands(toolchain: Stm32Toolchain, toolchainPath?: string): { configure?: string; build: string; clean: string } {
	if (toolchain === 'cmake') {
		const tp = toolchainPath ? ` -DTOOLCHAIN_PATH=${shellQuote(toolchainPath)}` : '';
		return {
			configure: `cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug${tp}`,
			build: `cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug${tp} && cmake --build build --parallel`,
			clean: 'cmake --build build --target clean',
		};
	}
	const tp = toolchainPath ? ` TOOLCHAIN_PATH=${shellQuote(toolchainPath)}` : '';
	return { build: `make -j${tp}`, clean: 'make clean' };
}

export function shellQuote(value: string): string {
	return /^[A-Za-z0-9_@%+=:,./-]+$/.test(value) ? value : `'${value.replace(/'/g, `'\\''`)}'`;
}

export function openocdArgs(spec: Stm32ProjectSpec): string[] {
	return ['-f', `interface/${spec.openocdInterface}.cfg`, '-f', `target/${spec.target.family.openocdTarget}.cfg`];
}

function elfPath(spec: Stm32ProjectSpec, id: string): string {
	return spec.toolchain === 'cmake' ? `build/${id}.elf` : `build/${id}.elf`;
}

function tasksJson(spec: Stm32ProjectSpec, id: string): string {
	const cmds = stm32BuildCommands(spec.toolchain);
	const tasks: unknown[] = [];
	if (cmds.configure) {
		tasks.push({ label: 'STM32: Configure', type: 'shell', command: cmds.configure, problemMatcher: [] });
	}
	tasks.push({ label: 'STM32: Build', type: 'shell', command: cmds.build, group: { kind: 'build', isDefault: true }, problemMatcher: ['$roboagent-gcc'] });
	tasks.push({ label: 'STM32: Clean', type: 'shell', command: cmds.clean, problemMatcher: [] });
	if (spec.kind === 'executable') {
		tasks.push({
			label: 'STM32: Flash (OpenOCD)', type: 'shell',
			command: `openocd ${openocdArgs(spec).join(' ')} -c "program ${elfPath(spec, id)} verify reset exit"`,
			dependsOn: 'STM32: Build', problemMatcher: [],
		});
	}
	return jsonFile({ version: '2.0.0', tasks });
}

/** Debug configurations: Cortex-Debug first (installed on first use), cpptools+OpenOCD as the fallback. */
export function stm32LaunchConfigurations(spec: Stm32ProjectSpec, id: string): Record<string, unknown>[] {
	const elf = '${workspaceFolder}/' + elfPath(spec, id);
	const ocd = openocdArgs(spec);
	return [
		{
			name: 'STM32: Debug (Cortex-Debug / OpenOCD)',
			type: 'cortex-debug',
			request: 'launch',
			servertype: 'openocd',
			cwd: '${workspaceFolder}',
			executable: elf,
			device: spec.target.part,
			configFiles: [ocd[1], ocd[3]],
			runToEntryPoint: 'main',
			preLaunchTask: 'STM32: Build',
		},
		{
			name: 'STM32: Debug (cpptools + OpenOCD GDB server)',
			type: 'cppdbg',
			request: 'launch',
			cwd: '${workspaceFolder}',
			program: elf,
			MIMode: 'gdb',
			miDebuggerPath: 'arm-none-eabi-gdb',
			miDebuggerServerAddress: 'localhost:3333',
			debugServerPath: 'openocd',
			debugServerArgs: ocd.join(' '),
			filterStderr: true,
			serverStarted: 'Listening on port 3333 for gdb connections',
			setupCommands: [
				{ text: 'monitor reset halt' },
				{ text: 'load' },
				{ text: 'monitor reset halt' },
				{ text: 'break main' },
			],
			preLaunchTask: 'STM32: Build',
		},
	];
}

function launchJson(spec: Stm32ProjectSpec, id: string): string {
	return jsonFile({ version: '0.2.0', configurations: stm32LaunchConfigurations(spec, id) });
}

function readme(spec: Stm32ProjectSpec, id: string): string {
	const t = spec.target;
	const build = stm32BuildCommands(spec.toolchain).build;
	return `# ${spec.name} — STM32 ${spec.kind} (${t.part})

${MARKER}

| | |
|---|---|
| MCU | **${t.part}** — ${t.family.label} (${t.core}) |
| Flags | \`${cpuFlags(t).join(' ')}\` |
| Memory | ${t.flashKb} KB flash / ${t.ramKb} KB RAM${t.exact ? '' : ' (defaults — part not in catalog, verify)'} |
| Toolchain | ${spec.toolchain === 'cmake' ? 'CMake + arm-none-eabi-gcc' : 'Makefile + arm-none-eabi-gcc'} |

## Build

\`\`\`bash
${build}
\`\`\`

Or press **Build** in the RoboAgent toolbar (Mode: STM32). Set \`roboagent.stm32.toolchainPath\` if
\`arm-none-eabi-gcc\` is not on your PATH.

${spec.kind === 'executable' ? `## Flash & debug

- **Debug** in the toolbar starts the \`STM32: Debug (Cortex-Debug / OpenOCD)\` configuration (interface \`${spec.openocdInterface}\`,
  target \`${t.family.openocdTarget}\`). Without Cortex-Debug, the cpptools + OpenOCD configuration is used.
- Task **STM32: Flash (OpenOCD)** programs \`${elfPath(spec, id)}\`.

## Next steps

Add the STM32Cube${t.family.id} HAL/CMSIS device pack (Drivers/, the real \`startup_${t.define.toLowerCase()}.s\`
and \`${t.part}_FLASH.ld\`) — the flags and .vscode setup already match ${t.part}.
` : `## Use

Link \`lib${id}.a\` (or \`add_subdirectory\` this folder) from an STM32 executable project built with the same MCU flags.
`}`;
}
