/*---------------------------------------------------------------------------------------------
 *  Copyright (c) RoboAgent. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

/*---------------------------------------------------------------------------------------------
 *  RoboAgent — ESP32 (ESP-IDF) project generator (pure: spec → files, no vscode).
 *
 *  Emits the canonical ESP-IDF layout (`CMakeLists.txt` including project.cmake, `main/`
 *  component, `sdkconfig.defaults` pinning CONFIG_IDF_TARGET) plus .vscode files for the
 *  bundled ESP-IDF extension and cpptools. `idf.py set-target` is run by the provider when an
 *  IDF environment is available; the sdkconfig.defaults makes the first build pick the chip
 *  even when it is not.
 *--------------------------------------------------------------------------------------------*/

import { FileSet, jsonFile, toIdentifier } from '../scaffold';

export type Esp32Chip = 'esp32' | 'esp32s2' | 'esp32s3' | 'esp32c3' | 'esp32c6' | 'esp32h2';

export const ESP32_CHIPS: ReadonlyArray<{ id: Esp32Chip; label: string; description: string; arch: 'xtensa' | 'riscv' }> = [
	{ id: 'esp32', label: 'ESP32', description: 'Xtensa LX6 dual-core, Wi-Fi + BT Classic/BLE', arch: 'xtensa' },
	{ id: 'esp32s2', label: 'ESP32-S2', description: 'Xtensa LX7 single-core, Wi-Fi, USB OTG', arch: 'xtensa' },
	{ id: 'esp32s3', label: 'ESP32-S3', description: 'Xtensa LX7 dual-core, Wi-Fi + BLE 5, AI vector extensions', arch: 'xtensa' },
	{ id: 'esp32c3', label: 'ESP32-C3', description: 'RISC-V single-core, Wi-Fi + BLE 5', arch: 'riscv' },
	{ id: 'esp32c6', label: 'ESP32-C6', description: 'RISC-V, Wi-Fi 6 + BLE 5 + 802.15.4 (Thread/Zigbee)', arch: 'riscv' },
	{ id: 'esp32h2', label: 'ESP32-H2', description: 'RISC-V, BLE 5 + 802.15.4 (no Wi-Fi)', arch: 'riscv' },
];

export function isEsp32Chip(value: unknown): value is Esp32Chip {
	return ESP32_CHIPS.some(c => c.id === value);
}

export type Esp32Template = 'hello_world' | 'blink';

export interface Esp32ProjectSpec {
	readonly name: string;
	readonly chip: Esp32Chip;
	readonly template: Esp32Template;
	/** Serial port to record in settings (optional). */
	readonly port?: string;
}

const MARKER = 'Generated by RoboAgent (Mode: ESP32).';

export function generateEsp32Project(spec: Esp32ProjectSpec): FileSet {
	const files = new Map<string, string>();
	const id = toIdentifier(spec.name);
	files.set('CMakeLists.txt', `# ${MARKER}
cmake_minimum_required(VERSION 3.16)

# The ESP-IDF build system: IDF_PATH must point at an ESP-IDF checkout (export.sh / the ESP-IDF extension).
include($ENV{IDF_PATH}/tools/cmake/project.cmake)
project(${id})
`);
	files.set('main/CMakeLists.txt', `idf_component_register(SRCS "main.c"
                       INCLUDE_DIRS "")
`);
	files.set('main/main.c', spec.template === 'blink' ? blinkMain(spec) : helloMain(spec));
	files.set('sdkconfig.defaults', `# ${MARKER}
# Pins the target so the first \`idf.py build\` (or \`idf.py set-target\`) uses ${spec.chip}.
CONFIG_IDF_TARGET="${spec.chip}"
`);
	files.set('.vscode/settings.json', jsonFile({
		'roboagent.mode': 'esp32',
		...(spec.port ? { 'roboagent.esp32.port': spec.port } : {}),
		'files.associations': { 'sdkconfig': 'ini', 'sdkconfig.defaults': 'ini' },
		'C_Cpp.default.compileCommands': '${workspaceFolder}/build/compile_commands.json',
		'C_Cpp.default.compilerPath': '',
	}));
	files.set('.vscode/c_cpp_properties.json', jsonFile({
		version: 4,
		configurations: [{
			name: 'ESP-IDF',
			compileCommands: '${workspaceFolder}/build/compile_commands.json',
			includePath: ['${workspaceFolder}/**', '${env:IDF_PATH}/components/**'],
			cStandard: 'c17',
			cppStandard: 'c++20',
			intelliSenseMode: 'linux-gcc-x86',
		}],
	}));
	files.set('.vscode/launch.json', jsonFile({
		version: '0.2.0',
		configurations: [esp32DebugConfiguration()],
	}));
	files.set('.vscode/tasks.json', jsonFile({
		version: '2.0.0',
		tasks: [
			{ label: 'ESP-IDF: Build', type: 'shell', command: esp32IdfCommand('build'), group: { kind: 'build', isDefault: true }, problemMatcher: ['$roboagent-gcc'] },
			{ label: 'ESP-IDF: Flash', type: 'shell', command: esp32IdfCommand('flash', spec.port), problemMatcher: [] },
			{ label: 'ESP-IDF: Monitor', type: 'shell', command: esp32IdfCommand('monitor', spec.port), problemMatcher: [], isBackground: true },
			{ label: 'ESP-IDF: Set target', type: 'shell', command: esp32IdfCommand(`set-target ${spec.chip}`), problemMatcher: [] },
		],
	}));
	files.set('.gitignore', 'build/\nsdkconfig.old\nmanaged_components/\ndependencies.lock\n');
	files.set('README.md', `# ${spec.name} — ESP-IDF project (${spec.chip})

${MARKER}

\`\`\`bash
# once per shell (or let the ESP-IDF extension manage it):
. $IDF_PATH/export.sh
idf.py set-target ${spec.chip}
idf.py build
idf.py -p /dev/ttyUSB0 flash monitor
\`\`\`

The RoboAgent **Build** button runs \`idf.py build\` through the bundled ESP-IDF extension when it is
configured (ESP-IDF: Configure extension), otherwise in a terminal after sourcing \`export.sh\` from
\`roboagent.esp32.idfPath\` / \`$IDF_PATH\`. **Debug** starts the extension's OpenOCD/GDB session
(\`gdbtarget\`) and falls back to flash + monitor when no board is attached.
`);
	files.set('.roboagent/project.json', jsonFile({ controlLevel: 'low', target: 'esp32', chip: spec.chip, createdWith: 'roboagent-mode-esp32' }));
	return files;
}

/** The ESP-IDF extension (2.x) debug configuration; the extension's provider fills in the rest. */
export function esp32DebugConfiguration(): Record<string, unknown> {
	return { type: 'gdbtarget', request: 'attach', name: 'Eclipse CDT GDB Adapter' };
}

/**
 * `idf.py <verb>` in a shell that has the IDF environment. `export.sh` is sourced from
 * `$IDF_PATH` so the same line works in tasks.json and in RoboAgent's terminal fallback.
 */
export function esp32IdfCommand(verb: string, port?: string, idfPath?: string): string {
	const idf = idfPath ? `IDF_PATH=${shellQuote(idfPath)}; export IDF_PATH; ` : '';
	const p = port ? ` -p ${shellQuote(port)}` : '';
	return `${idf}. "$IDF_PATH/export.sh" >/dev/null && idf.py${p} ${verb}`;
}

export function shellQuote(value: string): string {
	return /^[A-Za-z0-9_@%+=:,./-]+$/.test(value) ? value : `'${value.replace(/'/g, `'\\''`)}'`;
}

function helloMain(spec: Esp32ProjectSpec): string {
	return `/* ${MARKER} ${spec.name} — hello_world for ${spec.chip} */
#include <stdio.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_chip_info.h"
#include "esp_system.h"

void app_main(void)
{
    esp_chip_info_t chip_info;
    esp_chip_info(&chip_info);
    printf("Hello from RoboAgent on ${spec.chip}: %d core(s), revision %d\\n", chip_info.cores, chip_info.revision);

    for (int i = 10; i >= 0; i--) {
        printf("Restarting in %d seconds...\\n", i);
        vTaskDelay(pdMS_TO_TICKS(1000));
    }
    fflush(stdout);
    esp_restart();
}
`;
}

function blinkMain(spec: Esp32ProjectSpec): string {
	return `/* ${MARKER} ${spec.name} — blink for ${spec.chip} */
#include <stdio.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "driver/gpio.h"

#define BLINK_GPIO GPIO_NUM_2   /* adjust to your board's LED */

void app_main(void)
{
    gpio_reset_pin(BLINK_GPIO);
    gpio_set_direction(BLINK_GPIO, GPIO_MODE_OUTPUT);
    int level = 0;
    for (;;) {
        gpio_set_level(BLINK_GPIO, level);
        printf("LED %s\\n", level ? "on" : "off");
        level = !level;
        vTaskDelay(pdMS_TO_TICKS(500));
    }
}
`;
}
