/*---------------------------------------------------------------------------------------------
 *  Copyright (c) RoboAgent. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

/*---------------------------------------------------------------------------------------------
 *  RoboAgent — ROS 2 package generator (pure: spec → files, no vscode).
 *
 *  The ROS2 provider prefers `ros2 pkg create` (see {@link ros2PkgCreateArgs}) and then adds
 *  the launch file on top; when no ROS 2 installation is present, {@link generateRos2Package}
 *  produces an equivalent package (ament_cmake node, ament_python node, ament_cmake library,
 *  or interface package with msg/srv) so Create still works offline.
 *--------------------------------------------------------------------------------------------*/

import { FileSet, jsonFile } from '../scaffold';

export type Ros2BuildType = 'ament_cmake' | 'ament_python' | 'ament_cmake_library' | 'interface';

export const ROS2_BUILD_TYPES: ReadonlyArray<{ id: Ros2BuildType; label: string; description: string; icon: string }> = [
	{ id: 'ament_cmake', label: 'C++ node (ament_cmake)', description: 'rclcpp executable, installed to lib/<pkg>', icon: 'symbol-method' },
	{ id: 'ament_python', label: 'Python node (ament_python)', description: 'rclpy entry point via setup.py', icon: 'symbol-namespace' },
	{ id: 'ament_cmake_library', label: 'C++ library (ament_cmake)', description: 'Shared library + headers, exported for other packages', icon: 'library' },
	{ id: 'interface', label: 'Interface package (msg/srv)', description: 'rosidl message and service definitions', icon: 'symbol-interface' },
];

export const COMMON_ROS2_DEPENDENCIES: ReadonlyArray<{ id: string; description: string }> = [
	{ id: 'rclcpp', description: 'C++ client library' },
	{ id: 'rclpy', description: 'Python client library' },
	{ id: 'std_msgs', description: 'Standard message types' },
	{ id: 'sensor_msgs', description: 'Camera, LiDAR, IMU, joint states…' },
	{ id: 'geometry_msgs', description: 'Poses, twists, transforms' },
	{ id: 'nav_msgs', description: 'Odometry, paths, occupancy grids' },
	{ id: 'tf2_ros', description: 'Transform broadcasting and lookup' },
];

export interface Ros2PackageSpec {
	readonly name: string;
	readonly buildType: Ros2BuildType;
	readonly dependencies: readonly string[];
	/** Node executable name (cmake/python only); defaults to `<name>_node`. */
	readonly nodeName?: string;
	readonly description?: string;
	readonly maintainer?: string;
	readonly license?: string;
}

const MARKER = 'Generated by RoboAgent (Mode: ROS2).';

export function isValidRos2PackageName(name: string): boolean {
	return /^[a-z][a-z0-9_]*$/.test(name) && !name.includes('__') && !name.endsWith('_');
}

function nodeNameOf(spec: Ros2PackageSpec): string {
	return spec.nodeName ?? `${spec.name}_node`;
}

/** Dependencies a build type needs regardless of the user's picks. */
export function effectiveDependencies(spec: Ros2PackageSpec): string[] {
	const deps = new Set(spec.dependencies);
	if (spec.buildType === 'ament_cmake' || spec.buildType === 'ament_cmake_library') { deps.add('rclcpp'); }
	if (spec.buildType === 'ament_python') { deps.add('rclpy'); }
	if (spec.buildType === 'interface') { deps.delete('rclcpp'); deps.delete('rclpy'); }
	return [...deps];
}

/** Arguments for `ros2 pkg create` matching the spec (run inside `src/`). */
export function ros2PkgCreateArgs(spec: Ros2PackageSpec): string[] {
	const args = ['pkg', 'create', spec.name, '--license', spec.license ?? 'Apache-2.0'];
	if (spec.description) { args.push('--description', spec.description); }
	if (spec.maintainer) { args.push('--maintainer-name', spec.maintainer); }
	switch (spec.buildType) {
		case 'ament_cmake':
			args.push('--build-type', 'ament_cmake', '--node-name', nodeNameOf(spec));
			break;
		case 'ament_python':
			args.push('--build-type', 'ament_python', '--node-name', nodeNameOf(spec));
			break;
		case 'ament_cmake_library':
			args.push('--build-type', 'ament_cmake', '--library-name', spec.name);
			break;
		case 'interface':
			args.push('--build-type', 'ament_cmake');
			break;
	}
	const deps = effectiveDependencies(spec);
	if (deps.length > 0) {
		args.push('--dependencies', ...deps);
	}
	return args;
}

/** The launch file RoboAgent adds after `ros2 pkg create` (and in the offline generator). */
export function launchFile(spec: Ros2PackageSpec): string {
	const executable = nodeNameOf(spec);
	return `# ${MARKER}
from launch import LaunchDescription
from launch_ros.actions import Node


def generate_launch_description():
    return LaunchDescription([
        Node(
            package='${spec.name}',
            executable='${executable}',
            name='${executable}',
            output='screen',
        ),
    ])
`;
}

/** Files to add to a package created by `ros2 pkg create` (launch + install rule hint). */
export function ros2Extras(spec: Ros2PackageSpec): FileSet {
	const files = new Map<string, string>();
	if (spec.buildType === 'ament_cmake' || spec.buildType === 'ament_python') {
		files.set(`launch/${spec.name}.launch.py`, launchFile(spec));
	}
	files.set('.roboagent/package.json', jsonFile({ buildType: spec.buildType, createdWith: 'roboagent-mode-ros2' }));
	return files;
}

/** Full offline package (no `ros2` CLI available). */
export function generateRos2Package(spec: Ros2PackageSpec): FileSet {
	const files = new Map<string, string>(ros2Extras(spec));
	files.set('package.xml', packageXml(spec));
	const node = nodeNameOf(spec);
	switch (spec.buildType) {
		case 'ament_cmake':
			files.set('CMakeLists.txt', cmakeNode(spec, node));
			files.set(`src/${node}.cpp`, cppNode(spec, node));
			break;
		case 'ament_python':
			files.set('setup.py', setupPy(spec, node));
			files.set('setup.cfg', `[develop]\nscript_dir=$base/lib/${spec.name}\n[install]\ninstall_scripts=$base/lib/${spec.name}\n`);
			files.set(`resource/${spec.name}`, '');
			files.set(`${spec.name}/__init__.py`, '');
			files.set(`${spec.name}/${node}.py`, pyNode(spec, node));
			break;
		case 'ament_cmake_library':
			files.set('CMakeLists.txt', cmakeLibrary(spec));
			files.set(`include/${spec.name}/${spec.name}.hpp`, cppLibraryHeader(spec));
			files.set(`src/${spec.name}.cpp`, cppLibrarySource(spec));
			break;
		case 'interface':
			files.set('CMakeLists.txt', cmakeInterface(spec));
			files.set('msg/Status.msg', `# ${MARKER}\nstd_msgs/Header header\nstring state\nfloat32 battery_percent\n`);
			files.set('srv/SetMode.srv', `# ${MARKER}\nstring mode\n---\nbool success\nstring message\n`);
			break;
	}
	return files;
}

function packageXml(spec: Ros2PackageSpec): string {
	const deps = effectiveDependencies(spec);
	const buildTool = spec.buildType === 'ament_python' ? 'ament_python' : 'ament_cmake';
	const depLines = deps.map(d => `  <depend>${d}</depend>`).join('\n');
	const interfaceLines = spec.buildType === 'interface'
		? `  <buildtool_depend>rosidl_default_generators</buildtool_depend>\n  <depend>std_msgs</depend>\n  <exec_depend>rosidl_default_runtime</exec_depend>\n  <member_of_group>rosidl_interface_packages</member_of_group>\n`
		: '';
	const launchLine = spec.buildType === 'ament_cmake' || spec.buildType === 'ament_python' ? '  <exec_depend>ros2launch</exec_depend>\n' : '';
	return `<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>${spec.name}</name>
  <version>0.0.0</version>
  <description>${spec.description ?? `${spec.name} — ${MARKER}`}</description>
  <maintainer email="you@example.com">${spec.maintainer ?? 'you'}</maintainer>
  <license>${spec.license ?? 'Apache-2.0'}</license>

  <buildtool_depend>${buildTool}</buildtool_depend>
${interfaceLines}${depLines ? depLines + '\n' : ''}${launchLine}
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>${buildTool}</build_type>
  </export>
</package>
`;
}

function cmakeNode(spec: Ros2PackageSpec, node: string): string {
	const deps = effectiveDependencies(spec);
	return `cmake_minimum_required(VERSION 3.8)
project(${spec.name})
# ${MARKER}

if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  add_compile_options(-Wall -Wextra -Wpedantic)
endif()

find_package(ament_cmake REQUIRED)
${deps.map(d => `find_package(${d} REQUIRED)`).join('\n')}

add_executable(${node} src/${node}.cpp)
target_compile_features(${node} PUBLIC cxx_std_17)
ament_target_dependencies(${node} ${deps.join(' ')})

install(TARGETS ${node}
  DESTINATION lib/\${PROJECT_NAME})
install(DIRECTORY launch
  DESTINATION share/\${PROJECT_NAME})

if(BUILD_TESTING)
  find_package(ament_lint_auto REQUIRED)
  ament_lint_auto_find_test_dependencies()
endif()

ament_package()
`;
}

function cppNode(spec: Ros2PackageSpec, node: string): string {
	const className = node.split('_').map(s => s.charAt(0).toUpperCase() + s.slice(1)).join('');
	return `// ${MARKER}
#include <chrono>
#include <memory>

#include "rclcpp/rclcpp.hpp"
${spec.dependencies.includes('std_msgs') ? '#include "std_msgs/msg/string.hpp"\n' : ''}
using namespace std::chrono_literals;

class ${className} : public rclcpp::Node
{
public:
  ${className}() : Node("${node}")
  {
    timer_ = this->create_wall_timer(1s, [this]() {
      RCLCPP_INFO(this->get_logger(), "${spec.name}: tick %ld", count_++);
    });
  }

private:
  rclcpp::TimerBase::SharedPtr timer_;
  long count_ = 0;
};

int main(int argc, char ** argv)
{
  rclcpp::init(argc, argv);
  rclcpp::spin(std::make_shared<${className}>());
  rclcpp::shutdown();
  return 0;
}
`;
}

function setupPy(spec: Ros2PackageSpec, node: string): string {
	return `# ${MARKER}
from setuptools import find_packages, setup

package_name = '${spec.name}'

setup(
    name=package_name,
    version='0.0.0',
    packages=find_packages(exclude=['test']),
    data_files=[
        ('share/ament_index/resource_index/packages', ['resource/' + package_name]),
        ('share/' + package_name, ['package.xml']),
        ('share/' + package_name + '/launch', ['launch/${spec.name}.launch.py']),
    ],
    install_requires=['setuptools'],
    zip_safe=True,
    maintainer='${spec.maintainer ?? 'you'}',
    maintainer_email='you@example.com',
    description='${spec.description ?? spec.name}',
    license='${spec.license ?? 'Apache-2.0'}',
    entry_points={
        'console_scripts': [
            '${node} = ${spec.name}.${node}:main',
        ],
    },
)
`;
}

function pyNode(spec: Ros2PackageSpec, node: string): string {
	const className = node.split('_').map(s => s.charAt(0).toUpperCase() + s.slice(1)).join('');
	return `# ${MARKER}
import rclpy
from rclpy.node import Node


class ${className}(Node):
    def __init__(self):
        super().__init__('${node}')
        self.count = 0
        self.timer = self.create_timer(1.0, self.tick)

    def tick(self):
        self.get_logger().info(f'${spec.name}: tick {self.count}')
        self.count += 1


def main(args=None):
    rclpy.init(args=args)
    node = ${className}()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
`;
}

function cmakeLibrary(spec: Ros2PackageSpec): string {
	const deps = effectiveDependencies(spec);
	return `cmake_minimum_required(VERSION 3.8)
project(${spec.name})
# ${MARKER}

find_package(ament_cmake REQUIRED)
${deps.map(d => `find_package(${d} REQUIRED)`).join('\n')}

add_library(\${PROJECT_NAME} SHARED src/${spec.name}.cpp)
target_compile_features(\${PROJECT_NAME} PUBLIC cxx_std_17)
target_include_directories(\${PROJECT_NAME} PUBLIC
  $<BUILD_INTERFACE:\${CMAKE_CURRENT_SOURCE_DIR}/include>
  $<INSTALL_INTERFACE:include>)
ament_target_dependencies(\${PROJECT_NAME} ${deps.join(' ')})

install(TARGETS \${PROJECT_NAME}
  EXPORT export_\${PROJECT_NAME}
  ARCHIVE DESTINATION lib
  LIBRARY DESTINATION lib
  RUNTIME DESTINATION bin)
install(DIRECTORY include/ DESTINATION include)

ament_export_include_directories(include)
ament_export_targets(export_\${PROJECT_NAME} HAS_LIBRARY_TARGET)
ament_export_dependencies(${deps.join(' ')})

if(BUILD_TESTING)
  find_package(ament_lint_auto REQUIRED)
  ament_lint_auto_find_test_dependencies()
endif()

ament_package()
`;
}

function cppLibraryHeader(spec: Ros2PackageSpec): string {
	const guard = `${spec.name.toUpperCase()}__${spec.name.toUpperCase()}_HPP_`;
	return `// ${MARKER}
#ifndef ${guard}
#define ${guard}

#include <string>

namespace ${spec.name}
{

/// Example API exported by the ${spec.name} library.
std::string greet(const std::string & who);

}  // namespace ${spec.name}

#endif  // ${guard}
`;
}

function cppLibrarySource(spec: Ros2PackageSpec): string {
	return `// ${MARKER}
#include "${spec.name}/${spec.name}.hpp"

namespace ${spec.name}
{

std::string greet(const std::string & who)
{
  return "Hello, " + who + " — from ${spec.name}";
}

}  // namespace ${spec.name}
`;
}

function cmakeInterface(spec: Ros2PackageSpec): string {
	return `cmake_minimum_required(VERSION 3.8)
project(${spec.name})
# ${MARKER}

find_package(ament_cmake REQUIRED)
find_package(rosidl_default_generators REQUIRED)
find_package(std_msgs REQUIRED)

rosidl_generate_interfaces(\${PROJECT_NAME}
  "msg/Status.msg"
  "srv/SetMode.srv"
  DEPENDENCIES std_msgs
)

ament_export_dependencies(rosidl_default_runtime)
ament_package()
`;
}
